# Site settings
title: Documentación Claude Code
email: dev@trivance.ai
description: >-
  Guía completa de comandos, agentes y mejores prácticas para Claude Code.
  Aprende a usar herramientas AI-first para desarrollo profesional.

baseurl: "/trivance-ai-orchestrator" # the subpath of your site, e.g. /blog
url: "https://trivance-io.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages specific settings
github_username: trivance-ai
repository: trivance-ai-orchestrator

# Collections for documentation
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation structure
nav_sections:
  - title: "Comandos"
    url: "/commands/"
    icon: "terminal"
  - title: "Agentes"
    url: "/agents/"
    icon: "users"
  - title: "Workflows"
    url: "/workflows/"
    icon: "workflow"
  - title: "Mejores Prácticas"
    url: "/best-practices/"
    icon: "best-practices"

# Search settings
search:
  enabled: true
  placeholder: "Buscar en la documentación..."

# Performance settings
sass:
  style: compressed

# SEO and metadata
lang: es
author: Trivance AI Team

# Analytics (optional)
google_analytics: # Add your GA tracking ID here if needed

# Social links
social_links:
  github: https://github.com/trivance-ai/trivance-ai-orchestrator

# Build exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
